### ISSUE TITLE
Project Idea: TrailMix

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#15]
#### Description

As part of the PLATS conversion tool, we are going to produce a unique URLs for each batch of data uploaded---providing agencies with a way to return to the transformation process if they need additional time, information or data. 

This is a pattern we saw with [Streetmix](https://github.com/codeforamerica/streetmix) and now [TransitMix](https://github.com/codeforamerica/transitmix), where people create their own variations or permutations of a street or route.

Could we conceivably offer trail planners a similar planning tool? Uploading PLATS data would essentially serve as the creation of a base network from which additional trails could be explored.

At first blush, the value proposition seems a little vague. Trails tend to exist where they can---almost the archetypical embodiment of the "desire line" phenomenon. Nonetheless, trail planning is time-and-resource intensive part of land management.

This idea needs to be thought through some more before there are actionable steps.

**Comment by samhashemi** [comment]
Tempted to name my court app TrialMix

**Comment by alanjosephwilliams** [comment]
mix all the things!

**Comment by louh** [comment]
Recently on my radar (besides any mention of the search term *mix) is this method of creating unique citation IDs intended for academic reference (a common use case being citation of materials that might change URLs over time, but they seem to want to expand its use to potentially any digital object) - http://ezid.cdlib.org/

**Comment by junosuarez** [comment]
@louh I'm skeptical of identifiers which have to be issued by a centralized agency. For nearly all use cases, UUIDs work perfectly well. I know TransitMix went from longer IDs to integer serial numbers for the sake of readable URLs, but that's not really scalable long-term under heavy use. Beyond UUIDs, MongoDB ObjectIDs have the interesting property of being sortable by creation time, since the first several bits is just a time stamp. The last large content system I worked on featured elaborate (and forking) revision history control and leaned heavily on ObjectIDs.

**Comment by migurski** [comment]
Why wouldn’t integers be scalable? There’s loads of them.

If you don't want IDs to be guessable (can think of reasons for this) you might make short randomized values and prevent dupes with an IDs table. I’ve found UUIDs to be aesthetically challenging: they're very, very long for this purpose and can lead to some unsightly URLs.
