### ISSUE TITLE
Remove yellow “active development” bar

### ISSUE THREAD

**Issue by migurski** [codeforamerica/OpenTrails#55]
It’s really big, doesn’t add much. Move it to the bottom or shrink it to ~25px if it needs to be there.

**Comment by alanjosephwilliams** [comment]
My inclination was to provide an unavoidable message about the tool's stage of development. The alternative is to write copy that reinforces its state. Including (and removing) an alert seems like less overhead. We will want to update the README (#59) before the UC as well, since the alert links people to it.

Anyway, I reduced its prominence substantially (though not its position) via a55f113ffc2bacd238e2b99cddf3f2686c5ec912. I will close this ticket when the PR is merged.

**Comment by migurski** [comment]
Yeah the message is important, it was just pushing more salient things down the page. It might really only need to be there on the front-front?

**Comment by migurski** [comment]
Fixed in https://github.com/codeforamerica/PLATS/commit/098d39f3d09f99e6e52dc711132c70c76821cf0e.
